Refactor
nori-io/auth pull request #7
Opened 2020-12-04 12:25 UTC by bruteforce1414

2020-12-09 04:07 UTC, cheebo requested changes

2020-12-09 04:07 UTC, cheebo commented on asserts/sql/createTables.go
>  	CreateTableUsers = `CREATE TABLE IF NOT EXISTS users (
кажется этот файл можно удалить, у тебя sql код непосредственно в функциz[ install / uninstall

2020-12-09 04:07 UTC, cheebo commented on internal/domain/service/database/authModel.go
> +	ctx = context.Background()
так делать нельзя. нужно передавать контекст в функцию или использовать в нужном месте вызов context.Background

2020-12-09 04:07 UTC, cheebo commented on internal/domain/service/database/authModel.go
> +	ctx = context.Background()
Если нужен контекст внутри функций, то добавь в сигнатуру функции первым параметром `ctx context.Context`

2020-12-09 04:07 UTC, cheebo commented on internal/handler/http/endpoints.go
>  func MakeSignUpEndpoint(s Service) endpoint.Endpoint {
весь файл можно удалить, мы не используем сейчас endpoints и передаем в роутер непосредственно функции, которые у нас уже реализованы в другом файле

2020-12-09 04:07 UTC, cheebo commented on internal/handler/http/transport.go
> -	"github.com/nori-io/nori-common/transport/http"
этот файл тоже можно удалить, у нас создание роутов происходит в constructor.go

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/model.go
> +}
здесь у тебя у varchar указана максимальная длинна, и тебе нужно проверить есть ли такое sql коде в функции install.

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/model.go
> +	return &User{
у нас не может быть ошибки, поэтому можно убрать ее из списка возвращаемых параметров.

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +}
см документацию https://gorm.io/docs/create.html как создаются записи:
result := db.Create(&user) // pass pointer of data to Create
user.ID             // returns inserted data's primary key

тебе не нужно делать Scan на сколько я понимаю. В структуре, которую ты передаешь, уже будет заполнен ID который проставила база и остальные поля.

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +	e = r.Db.Where("id=?", id).First(out).Error
см https://gorm.io/docs/query.html выборку по первичному ключу
db.First(&user, 10)
// SELECT * FROM users WHERE id = 10;

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +
если у нас ошибка не nil, то мы не можем делать конвертацию. Нам нужно вернуть nil, error.
Переименуй e d err.

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +
или сделай 
```if  err := r.Db.Where("email=?", email).First(out).Error; err != nil { ```

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +	for i, v := range out {
нет обработки ошибки. если ошибка не nil - нужно сразу вернуть nil, err

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +		e           error
e -> err или см подход выше

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +	err := r.Db.Save(model).Error
обработка ошибки как выше

2020-12-09 04:07 UTC, cheebo commented on internal/repository/user/postgres/repo.go
> +
пустые строки. см форматирование, не должно быть лишних пустых строк. file watchers настроены в goland?

2020-12-09 04:07 UTC, cheebo commented on internal/service/auth/auth.go
> +
пустые строки

2020-12-09 04:07 UTC, cheebo commented on internal/service/auth/auth.go
> +
пустая строка.

2020-12-09 04:07 UTC, cheebo commented on internal/service/auth/auth.go
> +
пустая строка

2020-12-09 04:07 UTC, cheebo commented on internal/service/auth/auth.go
> +	}
```
if err := err = srv.db.Create(ctx, user); err != nil {
 return nil, err
}

2020-12-09 04:07 UTC, cheebo commented on internal/service/auth/auth.go
> +
пустая строка, не красиво :)

2020-12-09 04:07 UTC, cheebo commented on internal/service/auth/auth.go
> +	}
давай писать в более компактном виде:
```
if err := data.Validate(); err != nil {
  		return nil, err
}

2020-12-10 05:54 UTC, bruteforce1414 commented on asserts/sql/createTables.go
>  	CreateTableUsers = `CREATE TABLE IF NOT EXISTS users (
может тогда вообще всю папку asserts?

2020-12-10 08:18 UTC, bruteforce1414 commented on asserts/sql/createTables.go
>  	CreateTableUsers = `CREATE TABLE IF NOT EXISTS users (
deleted

2020-12-10 08:22 UTC, bruteforce1414 commented on internal/handler/http/endpoints.go
>  func MakeSignUpEndpoint(s Service) endpoint.Endpoint {
deleted endpoints.go

2020-12-10 08:26 UTC, bruteforce1414 commented on internal/handler/http/transport.go
> -	"github.com/nori-io/nori-common/transport/http"
deleted

2020-12-10 08:28 UTC, bruteforce1414 commented on internal/repository/user/postgres/model.go
> +}
Есть, но в sql коде я указала 32, изменю здесь тоже до 32

2020-12-10 08:31 UTC, bruteforce1414 commented on internal/service/auth/auth.go
> +
fix

2020-12-10 08:32 UTC, bruteforce1414 commented on internal/service/auth/auth.go
> +
fix

2020-12-10 08:36 UTC, bruteforce1414 commented on internal/service/auth/auth.go
> +
fix

2020-12-10 09:01 UTC, bruteforce1414 commented on internal/domain/service/database/authModel.go
> +	ctx = context.Background()
папка с этим кодом удалена в виду неактуальности

2020-12-10 09:02 UTC, bruteforce1414 commented on internal/service/auth/auth.go
> +	}
fix

2020-12-10 09:02 UTC, bruteforce1414 commented on internal/service/auth/auth.go
> +	}
fix in all the code

2020-12-15 04:01 UTC, cheebo approved these changes

2020-12-15 04:02 UTC, merged